version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./app/instance:/app/instance
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///instance/emails.db
      - GITHUB_REPO_PATH=/app/data
      - SYNC_INTERVAL_MINUTES=${SYNC_INTERVAL_MINUTES:-30}
      - FLASK_ENV=${FLASK_ENV:-production}
    restart: unless-stopped
    depends_on:
      - email-sender

  email-sender:
    build:
      context: ./email_sender
      dockerfile: Dockerfile
    volumes:
      - ./app/instance:/app/instance
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///instance/emails.db
      - GITHUB_REPO_PATH=/app/data
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - EMAIL_DELAY_SECONDS=${EMAIL_DELAY_SECONDS:-5}
      - BATCH_DELAY_SECONDS=${BATCH_DELAY_SECONDS:-120}
      - BATCH_SIZE=${BATCH_SIZE:-100}
    restart: unless-stopped

volumes:
  data:
